### PR TITLE
Display rotated hkls in sim_view

### PR DESCRIPTION
**Pull request by mewall**

### CODE REVIEW

**Review by irisdyoung — COMMENTED** [review]
I recall some issue with using ceiling before for finding the nearest hkl -- in this use case is this the behavior we want?

**Comment by mewall** [comment]
That's the way it's currently done in diffBragg. I think we tried using round() as well but that didn't make it into the code...as I recall there are (very limited) cases where they give different answers.

________________________________
From: Iris Young ***@***.***>
Sent: Wednesday, August 24, 2022 2:54:31 PM
To: dermen/sim_erice
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [dermen/sim_erice] Display rotated hkls in sim_view (PR #6)


@irisdyoung commented on this pull request.

I recall some issue with using ceiling before for finding the nearest hkl -- in this use case is this the behavior we want?

**Review by dermen — COMMENTED** [review]
looks good, can we just replace/remove the original method  ..

**Comment by mewall** [comment]
force-pushed a revision

________________________________

**Comment by dermen** [comment]
looks good to me! Now, lets add a "run diffBragg" button :)

**Comment by mewall** [comment]
Yes, I can do that.

________________________________
From: Derek Mendez ***@***.***>
Sent: Wednesday, August 24, 2022 5:09:32 PM
To: dermen/sim_erice
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [dermen/sim_erice] Display rotated hkls in sim_view (PR #6)


@dermen commented on this pull request.

looks good, can we just replace the original method ?

**Pull request merged**
